---
title: "ExcessMort_Euro"
output: html_document
---

```{r setup, include=FALSE}
library(data.table)
library(ggplot2)
library(segmented)
library(rstanarm)
library(doBy)
library(dplyr)
library(forecast)
library(gridExtra)
library(ggthemes)
```

```{r functions, echo=F}
downloadLatest <- function(x){
  d <- fread('https://ec.europa.eu/eurostat/api/dissemination/sdmx/2.1/data/demo_r_mwk_20?format=TSV&compressed=true', header = T)
  setnames(d, 1, 'key')
  d$id <- 1:nrow(d)
  
  
  key <- strsplit(d$key, ',') |> 
    unlist() |>
    matrix(ncol=5, byrow=T) |>
    data.table()
  setnames(key, c('freq', 'age', 'sex', 'unit', 'geo'))
  key$id <- 1:nrow(key)
  
  # freq is week and unit = NR for all rows. Drop
  key <- select(key, -c(freq, unit))
  
  ## clean up values and create a variable for provisional flag
  d <- melt(d, id.vars=c('id', 'key'), variable.name = 'week', variable.factor=F) |>
    select(-key) |>
    mutate(value=gsub(':', NA, value)) |> ## missing
    mutate(provisional = if_else(grepl('p', value), T, F),
           value=gsub('p', '', value)) |>
    mutate(value=as.integer(trimws(value)))
  
  ## map weeks to date-of-week-start
  dates <- data.frame(week=unique(d$week)) |>
    mutate(date=ISOweek::ISOweek2date(paste0(week, '-1')))
  
  d <- merge(d, dates, by='week') 
  rm(dates)
  
  
  merge(d, key[!age %in% c('UNK', 'Y80-89', 'Y_GE90') ], by = 'id') |>
    select(-id)
  
}

getQuantiles <- function(x, req.qs=c(0.025, 0.05, seq(0.1, 0.9, by=.1), .95, .975, 0.25, 0.75)){
  x <- apply(x, 1, function(y) quantile(y, req.qs)) |> t()
  colnames(x) <- paste0('q_', req.qs)
  
  x
}

processAgg <- function(x){
  x <- dcast(x, geo+age+sex+year+date+deaths+pop~variable)
  
  data.table(dplyr::select(x, geo, age, sex, year, date, deaths, pop),
             dplyr::select(x, -c(geo, age, sex, year, date, deaths, pop))|> as.matrix() |> getQuantiles(),
             pr=dplyr::select(x, -c(geo, age, sex, year, date, deaths, pop))|> as.matrix() |> 
               apply(1, function(y) round(sum(y > 0)/length(y), 4)))
}

# Using segmented regression following STL decomposition
altTrend <- function(d2, train.start, train.end){
  splitBy(~age+sex, d2) |>
    lapply(function(x){
      
      train.age <<- filter(x, date >= train.start, date < train.end) ## Making global as selgmented throws error saying it is unable to find data object used for GLM.
      test.age <<- filter(x, date >= train.end) 
      
      ### Find trend in mortality rate using STL decomposition 
      x.stl <- train.age$rate %>%
        ts(frequency=52) %>%
        stats::stl(s.window = 'periodic')
      train.age$trend.stl <<- forecast::trendcycle(x.stl)  # fit
      
      ### find breakpoints in the trend
      glm.seg <- glm(trend.stl~trend, data=train.age, family=gaussian())
      
      seg.model <- selgmented(glm.seg, seg.Z=~trend, msg=F)
      
      
      n.breaks <- seg.model$selection.psi$npsi
      if(n.breaks > 0){
        train.age$trend <- seg.model$fitted.values ## Overwrite default trend (simple sequence)
        
        final.slope <- slope(seg.model)$trend[, 'Est.'] |> tail(1)
        final.intercept <- intercept(seg.model)$trend[, 'Est.'] |> tail(1)
        test.age$trend <- test.age$trend*final.slope + final.intercept ## assume the last known slope+intercept continues through the forecast period (?)
      } 
      
      rbind(dplyr::select(train.age, -trend.stl), test.age)
    }) |> 
    rbindlist()
}

fitModel <- function(d, train.start='2010-01-01', train.end='2020-01-01', segmented.trend=F){
  d <- d[age != 'TOTAL' & sex != 'T'] ## we do not want these aggregated strata in the model
  
  if(segmented.trend == T){
    d <- altTrend(d, train.start, train.end)
  }
  
  train <- filter(d, date >= train.start, date < train.end)
  test <- filter(d, date >= train.end) |>
    mutate(deaths=if_else(is.na(deaths), 0, deaths))
  
  
  model <- rstanarm::stan_glm.nb(
    deaths ~ offset(log(pop)) + # age-specific population offset
      age + sex + trend + seasonality + age:sex + sex:trend + age:trend + age:seasonality,
    data = train,
    chains = 4, 
    seed = 3542
  )
  
  ## inspect model
  # shinystan::launch_shinystan(model)
  
  fit <- rstanarm::posterior_predict(
    model,
    newdata=train,
    offset=log(train$pop)
  )
  
  ### Fitted deaths at the leaf nodes
  fit.leaves <- data.table(subset(train, select=c(age, sex, geo, year, date, deaths, pop)), getQuantiles(t(fit)))
  ### Aggregate up the tree
  fit.agg <- melt(data.table(subset(train, select=c(age, sex, geo, year, date, deaths, pop)), t(fit)), 
                  id.vars = c('age', 'sex', 'geo', 'year', 'date', 'deaths', 'pop'))
  fit.agg <- rbind(fit.agg[, j=.(age='TOTAL', sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), 
                           by=.(geo,  year, date, variable)]|> processAgg(),
                   fit.agg[, j=.(age='TOTAL', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), 
                           by=.(geo, sex,  year, date, variable)]|> processAgg(),
                   fit.agg[, j=.(sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), 
                           by=.(geo, age, year, date, variable)]|> processAgg())|> 
    dplyr::select(!pr)
  
  fit.agg <- rbind(fit.leaves, fit.agg)
  
  
  
  ### Get posterior over projection period
  pred <- rstanarm::posterior_predict(
    model,
    newdata=test,
    offset=log(test$pop)
  )
  
  ### Expected deaths at the leaf nodes
  pred.leaves <- data.table(subset(test, select=c(age, sex, geo, year, date, deaths, pop)), getQuantiles(t(pred)))
  
  ### Excess deaths at the leaf nodes
  excess.leaves <- melt(data.table(subset(test, select=c(age, sex, geo, year, date, deaths, pop)), t(pred)), 
                        id.vars = c('age', 'sex', 'geo', 'year', 'date', 'deaths', 'pop')) |>
    mutate(value=(deaths-value)) |>
    processAgg()
  
  
  
  ### Aggregate up the tree
  
  pred.agg <- melt(data.table(subset(test, select=c(age, sex, geo, year, date, deaths, pop)), t(pred)), 
                   id.vars = c('age', 'sex', 'geo', 'year', 'date', 'deaths', 'pop'))
  
  ## Aggregate posteriors of EXCESS across age groups and sex + stack
  excess.agg <- rbind(
    excess.leaves,
    pred.agg[, j=.(age='TOTAL', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, sex, year, date, variable)] |> 
      mutate(value=(deaths-value)) |> processAgg(),
    pred.agg[, j=.(sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, age, year, date, variable)]|> 
      mutate(value=(deaths-value)) |> processAgg(),
    pred.agg[, j=.(age='TOTAL', sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, year, date, variable)]|> 
      mutate(value=(deaths-value)) |>processAgg()
  )
  
  
  ## Aggregate posteriors of EXPECTED across age groups and sex + stack
  pred.agg <- rbind(
    pred.leaves,
    pred.agg[, j=.(age='TOTAL', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, sex, year, date, variable)] |> 
      processAgg() |>  dplyr::select(!pr), # combine ages
    pred.agg[, j=.(sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, age, year, date, variable)]|> 
      processAgg() |>  dplyr::select(!pr), # combine sex
    pred.agg[, j=.(age='TOTAL', sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, year, date, variable)]|> 
      processAgg() |>  dplyr::select(!pr) #combine age+sex
  )
  
  list(pred.agg, excess.agg, fit.agg)

}

fitModelGAMM <- function(d, train.start='2010-01-01', train.end='2020-01-01'){
  d <- d[age != 'TOTAL' & sex != 'T'] ## we do not want these aggregated strata in the model
  
  ### the s() function in GAMM model can only take a single variable (?), so creating a new combination variable
  d <- mutate(d, age_sex=paste0(age, '-', sex) |> factor(),
              age=factor(age))
  
  train <- filter(d, date >= train.start, date < train.end)
  test <- filter(d, date >= train.end) |>
    mutate(deaths=if_else(is.na(deaths), 0, deaths))
  
  
  
  model <- rstanarm::stan_gamm4(
    deaths ~ offset(log(pop)) + # group-specific population offset
      s(year, k = length(unique(train$year)), by=age_sex) + # annual trend
      s(week, bs = "cc", k = 52, by=age) + # cyclic spline for seasonality (assume no difference in seasonality by sex within age)
      age_sex, #  variable for leaf nodes age + sex 
    data = train,
    family = neg_binomial_2(link='log'),
    chains=2,
    QR=T,
    seed = 3542
  )
  
  ## inspect model
  # shinystan::launch_shinystan(model)

  
  
  fit <- rstanarm::posterior_predict(
    model,
    newdata=train,
    offset=log(train$pop)
  )
  
  ### Fitted deaths at the leaf nodes
  fit.leaves <- data.table(subset(train, select=c(age, sex, geo, year, date, deaths, pop)), getQuantiles(t(fit)))
  ### Aggregate up the tree
  fit.agg <- melt(data.table(subset(train, select=c(age, sex, geo, year, date, deaths, pop)), t(fit)), 
                  id.vars = c('age', 'sex', 'geo', 'year', 'date', 'deaths', 'pop'))
  fit.agg <- rbind(fit.agg[, j=.(age='TOTAL', sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), 
                           by=.(geo,  year, date, variable)]|> processAgg(),
                   fit.agg[, j=.(age='TOTAL', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), 
                           by=.(geo, sex,  year, date, variable)]|> processAgg(),
                   fit.agg[, j=.(sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), 
                           by=.(geo, age, year, date, variable)]|> processAgg())|> 
    dplyr::select(!pr)
  
  fit.agg <- rbind(fit.leaves, fit.agg)
  
  
  
  
  ### Get posterior over projection period
  pred <- rstanarm::posterior_predict(
    model,
    newdata=test,
    offset=log(test$pop)
  )
  
  ### Expected deaths at the leaf nodes
  pred.leaves <- data.table(subset(test, select=c(age, sex, geo, year, date, deaths, pop)), getQuantiles(t(pred)))
  
  ### Excess deaths at the leaf nodes
  excess.leaves <- melt(data.table(subset(test, select=c(age, sex, geo, year, date, deaths, pop)), t(pred)), 
                        id.vars = c('age', 'sex', 'geo', 'year', 'date', 'deaths', 'pop')) |>
    mutate(value=(deaths-value)) |>
    processAgg()
  
  
  
  ### Aggregate up the tree
  pred.agg <- melt(data.table(subset(test, select=c(age, sex, geo, year, date, deaths, pop)), t(pred)), 
                   id.vars = c('age', 'sex', 'geo', 'year', 'date', 'deaths', 'pop'))
  
  ## Aggregate posteriors of EXCESS across age groups and sex + stack
  excess.agg <- rbind(
    excess.leaves,
    pred.agg[, j=.(age='TOTAL', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, sex, year, date, variable)] |> 
      mutate(value=(deaths-value)) |> processAgg(),
    pred.agg[, j=.(sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, age, year, date, variable)]|> 
      mutate(value=(deaths-value)) |> processAgg(),
    pred.agg[, j=.(age='TOTAL', sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, year, date, variable)]|> 
      mutate(value=(deaths-value)) |>processAgg()
  )
  
  
  ## Aggregate posteriors of EXPECTED across age groups and sex + stack
  pred.agg <- rbind(
    pred.leaves,
    pred.agg[, j=.(age='TOTAL', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, sex, year, date, variable)] |> 
      processAgg() |>  dplyr::select(!pr), # combine ages
    pred.agg[, j=.(sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, age, year, date, variable)]|> 
      processAgg() |>  dplyr::select(!pr), # combine sex
    pred.agg[, j=.(age='TOTAL', sex='T', value=sum(value), pop=sum(pop), deaths=sum(deaths, na.rm = T)), by=.(geo, year, date, variable)]|> 
      processAgg() |>  dplyr::select(!pr) #combine age+sex
  )
  
  list(pred.agg, excess.agg, fit.agg)
  
}

```


```{r modelBuild, echo=FALSE}
setwd('C:/fhi/excess_mortality/manuscript/realtime/')
options(mc.cores=parallel::detectCores())

#####

d <- fread('Eurostat.csv') |>
  mutate(week = substring(week, 7) |> as.integer(),
         seasonality = sin(2*pi*week/52.14) + cos(2*pi*week/52.14)) |> ## Serfling formulation
  arrange(geo, age, sex, date)

d$trend <- ave(as.numeric(d$date), d$geo, d$age, d$sex, FUN=seq_along) 


### set the location of interest, end of training period and type of model
req.loc <- 'FI' ## One of following : c('AT', 'BE', 'BG', 'CH', 'EE', 'ES', 'FI', 'HR', 'HU', 'IS', 'LT', 'LV', 'NL', 'NO', 'PL', 'PT', 'SE', 'SI', 'SK')
req.train.end <- as.Date('2019-12-31')
req.model <- 'GLM'

if(req.model=='GLM'){
  ## build a model, can take 1+ hour
  # model <- fitModel(d[geo == req.loc], train.end = req.train.end, segmented.trend = T)
  
  ## Or load saved model
  load('results/EU/Models_GLM_FI.RData')
  model <- glm.models[[which(names(glm.models)==req.train.end)]]
  rm(glm.models)
} else{
  ## build a model, can take 1+ hour
  model <- fitModelGAMM(d[geo == req.loc], train.end = req.train.end)
  
  ## load saved model
  # load('results/EU/Models_GAM_FI.RData')
  # model <- gam.models[[which(names(gam.models)==req.train.end)]]
  # rm(gam.models)
}

print(paste0('Location:', req.loc, ' | Training end:', req.train.end, ' | Model:', req.model), quote=F)
```

#### Overall model fit and projection  + excess estimate    

```{r plot1, echo=FALSE, fig.width=8, fig.height=8}
age.levels.eu <- c('TOTAL', 'Y_LT20', 'Y20-39', 'Y40-59', 'Y60-79', 'Y_GE80')
sex.levels <- c('T', 'F', 'M')
req.levels <- paste0(rep(c('sex=Total', 'sex=Women', 'sex=Men'), each=length(age.levels.eu)), '|age=', age.levels.eu)

pred <- mutate(model[[1]], age=factor(age, age.levels.eu))
excess <- mutate(model[[2]], age=factor(age, age.levels.eu))
fit <- mutate(model[[3]], age=factor(age, age.levels.eu))

d2 <- filter(excess, age == 'TOTAL', sex == 'T', date < '2024-06-01') |> mutate(model=req.model)
p1 <- ggplot(d2) +
  geom_line(aes(x=date, y=q_0.5, color=model)) +
  geom_ribbon(aes(x=date, ymin=q_0.25, ymax=q_0.75, fill=model), alpha=.4) +
  geom_ribbon(aes(x=date, ymin=q_0.025, ymax=q_0.975, fill=model), alpha=.2) +
  geom_point(data=filter(d2,  pr > .95), aes(x=date, y=0, color=model), shape=1, size=.9, color='darkgreen') +
  scale_fill_manual(values=c( 'red')) +
  scale_color_manual(values=c('red')) +
  geom_hline(aes(yintercept=0), linetype='dashed') +
  guides(color='none', fill='none') +
  scale_y_continuous(labels = scales::label_number(scale=1e-3)) +
  labs(x='Date', y='Excess deaths, count (thousands)') +
  theme_clean() + theme(legend.position = 'bottom', axis.title=element_text(size=14, family='serif'), strip.text = element_text(size=14, family='serif'),
                        axis.text.y=element_text(size=8, family='serif'), panel.background = element_rect())
  
p2 <- rbind(filter(fit, age == 'TOTAL', sex == 'T') |> mutate(period='fit'),
            filter(pred, age == 'TOTAL', sex == 'T') |> mutate(period='pred')) |>
  filter(date < '2024-06-01') |>
  ggplot() +
  geom_line(aes(x=date, y=q_0.5, color=period)) +
  geom_point(aes(x=date, y=deaths, color=period), size=.5) +
  geom_ribbon(aes(x=date, ymin=q_0.25, ymax=q_0.75, fill=period), alpha=.7) +
  geom_ribbon(aes(x=date, ymin=q_0.025, ymax=q_0.975, fill=period), alpha=.3) +
  geom_vline(xintercept=as.Date(req.train.end), linetype='dashed') +
  scale_fill_manual(values=c('lightblue', 'orange')) +
  scale_color_manual(values=c('darkblue', 'indianred')) +
  guides(color='none', fill='none') +
  scale_y_continuous(labels = scales::label_number(scale=1e-3)) +
  labs(x='Date', y='Expected deaths, count (thousands)') +
  theme_clean() + theme(legend.position = 'bottom', axis.title=element_text(size=14, family='serif'), strip.text = element_text(size=14, family='serif'),
                        axis.text.y=element_text(size=8, family='serif'), panel.background = element_rect())

grid.arrange(p2, p1, ncol=1) # 1400 x 900

```

#### Fit and projection by age+sex group    
    
    
```{r plot2, echo=FALSE, fig.width=16, fig.height=12}
rbind(filter(fit) |> mutate(period='fit'),
      filter(pred) |> mutate(period='pred')) |>
  filter(date < '2024-06-01', date > '2016-01-01') |>
    mutate(sex=factor(sex, levels=sex.levels, labels=c('Total', 'Women', 'Men')),
         sex_age=factor(paste0('sex=', sex, '|', 'age=',age), levels=req.levels)) |>
  ggplot() +
  geom_line(aes(x=date, y=q_0.5, color=period)) +
  geom_point(aes(x=date, y=deaths, color=period), size=.5) +
  geom_ribbon(aes(x=date, ymin=q_0.25, ymax=q_0.75, fill=period), alpha=.7) +
  geom_ribbon(aes(x=date, ymin=q_0.025, ymax=q_0.975, fill=period), alpha=.3) +
  geom_vline(xintercept=as.Date(req.train.end), linetype='dashed') +
  scale_fill_manual(values=c('lightblue', 'orange')) +
  scale_color_manual(values=c('darkblue', 'indianred')) +
  scale_y_continuous(labels = scales::label_number(scale=1e-3)) +
  facet_wrap(~sex_age, scales='free', ncol=length(age.levels.eu)) + guides(color='none', fill='none') +
  labs(x='Date', y='Expected deaths, count (thousands)', title=req.loc) +
  theme_clean() + theme(legend.position = 'bottom', axis.title=element_text(size=14, family='serif'), strip.text = element_text(size=14, family='serif'),
                        axis.text.y=element_text(size=8, family='serif'), panel.background = element_rect())

```
    
#### Excess estimate by age+sex group    

    
```{r plot3, echo=FALSE, fig.width=16, fig.height=12}
d2 <- filter(excess, date < '2024-06-01') |> 
  mutate(model=req.model) |>
    mutate(sex=factor(sex, levels=sex.levels, labels=c('Total', 'Women', 'Men')),
         sex_age=factor(paste0('sex=', sex, '|', 'age=',age), levels=req.levels))
ggplot(d2) +
  geom_line(aes(x=date, y=q_0.5, color=model)) +
  geom_ribbon(aes(x=date, ymin=q_0.25, ymax=q_0.75, fill=model), alpha=.4) +
  geom_ribbon(aes(x=date, ymin=q_0.025, ymax=q_0.975, fill=model), alpha=.2) +
  geom_point(data=filter(d2,  pr > .95), aes(x=date, y=0, color=model), shape=1, size=.9, color='darkgreen') +
  scale_fill_manual(values=c( 'red')) +
  scale_color_manual(values=c('red')) +
  geom_hline(aes(yintercept=0), linetype='dashed') +
  facet_wrap(~sex_age, scales='free', ncol=length(age.levels.eu)) + guides(color='none', fill='none') +
  scale_y_continuous(labels = scales::label_number(scale=1e-3)) +
  labs(x='Date', y='Excess deaths, count (thousands)', title=req.loc) +
  theme_clean() + theme(legend.position = 'bottom', axis.title=element_text(size=14, family='serif'), strip.text = element_text(size=14, family='serif'),
                        axis.text.y=element_text(size=8, family='serif'), panel.background = element_rect())
```
    
#### Probability of excess by age+sex group    

    
```{r plot4, echo=FALSE, fig.width=12, fig.height=6}
filter(excess, date < '2024-06-01') |>
    mutate(sex=factor(sex, levels=sex.levels, labels=c('Total', 'Women', 'Men'))) |>
  ggplot() +
  geom_raster(aes(x=date, y=age, fill=pr)) +
  scale_fill_gradient2(low='darkblue', high='#bd0026', midpoint=.5, mid='#fecc5c') +
  facet_wrap(~sex, scales='free', ncol=1) + 
  geom_vline(xintercept=as.Date(req.train.end), linetype='dashed', linewidth=.25)+
  labs(x='Date', fill= 'Probability of excess mortality', y= 'Age group') +
  theme_clean() + theme(legend.position = 'bottom', panel.background = element_rect(fill = NULL), 
                        strip.text = element_text(size=14, family='serif'), axis.text.y = element_text(size=12, family = 'serif'),
                        axis.title = element_text(size=14, family='serif'), legend.text = element_text(size=8))
```
